/*global define */
/*jslint browser:true,sloppy:true,nomen:true,unparam:true,plusplus:true,indent:4 */
/*
 | Copyright 2013 Esri
 |
 | Licensed under the Apache License, Version 2.0 (the "License");
 | you may not use this file except in compliance with the License.
 | You may obtain a copy of the License at
 |
 |    http://www.apache.org/licenses/LICENSE-2.0
 |
 | Unless required by applicable law or agreed to in writing, software
 | distributed under the License is distributed on an "AS IS" BASIS,
 | WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 | See the License for the specific language governing permissions and
 | limitations under the License.
 */
define({
    tocContentsCaption: "@@fr@@ Contents",
    homeTitle: "@@fr@@ Home",
    addPageTitle: "@@fr@@ Add Page",
    alertDialogTitle: "@@fr@@ Alert",
    confirmDialogTitle: "@@fr@@ Confirm",
    refreshBookTitle: "@@fr@@ Refresh",
    editTitle: "@@fr@@ Edit Book",
    deleteTitle: "@@fr@@ Delete Page",
    descriptionNotAvailable: "@@fr@@ summary is not available",
    removeBookTitle: "@@fr@@ Remove Book",
    tocTitle: "@@fr@@ Contents",
    addPageText: "@@fr@@ Add",
    addBookTitle: "@@fr@@ New Book",
    saveBookTitle: "@@fr@@ Save Book",
    copyBookTitle: "@@fr@@ Copy Book",
    defaultItemId: "@@fr@@ newItem",
    contentsPageTitle: "@@fr@@ Contents",
    pageText: "@@fr@@ Page ",
    ofText: "@@fr@@ of ",
    okButtonText: "@@fr@@ OK",
    saveButtonText: "@@fr@@ Save",
    cancelButtonText: "@@fr@@ Cancel",
    closeButtonTitle: "@@fr@@ Close",
    untitled: "@@fr@@ Untitled",
    legendTitle: "@@fr@@ Legend",
    fullScreen: "@@fr@@ Toggle full screen",
    dndModuleText: "@@fr@@ Drag and Drop Modules",
    selectAnyLayout: "@@fr@@ Select a page layout",
    fieldIsEmpty: "@@fr@@ Field can not be empty",
    webMapIconTitle: "@@fr@@ Map",
    freeFormIconTitle: "@@fr@@ HTML",
    textAreaIconTitle: "@@fr@@ Text Area",
    imageIconTitle: "@@fr@@ Image",
    videoIconTitle: "@@fr@@ Video",
    flickrIconTitle: "@@fr@@ Flickr",
    editMentEditTitle: "@@fr@@ Edit",
    editMentDeleteTitle: "@@fr@@ Delete",
    confirmModuleDeleting: "@@fr@@ Do you want to delete this module?",
    authorName: "@@fr@@ Author name",
    settingDialogTitle: "@@fr@@ Edit ${modType}",
    mapbookDefaultTitle: "@@fr@@ Briefing Book Title Goes Here",
    confirmPageDeleting: "@@fr@@ This page will be removed. Click Ok to confirm.",
    confirmCopyOfSelectedBook: "@@fr@@ Do you want to copy this book?",
    confirmDeletingOfSelectedBook: "@@fr@@ ${bookName} will be removed. Click 'OK' to confirm removal.",
    confirmAppReloading: "@@fr@@ Briefing book gallery will be reloaded and you may lose the edits.",
    validateBookOwner: "@@fr@@ You do not have permission to edit this book.",
    validateOrganizationUser: "@@fr@@ You are not the member of this Organization.",
    copyKeyword: "@@fr@@ Copy - ",
    signInText: "@@fr@@ Sign In",
    signOutText: "@@fr@@ Sign Out",
    searchWebmapPlaceHolder: "@@fr@@ Enter search term",
    nextWebmapPageText: "@@fr@@ Next",
    preWebmapPageText: "@@fr@@ Previous",
    validateUnSavedEdits: '@@fr@@ There are unsaved changes in this book. Click "Cancel" to stay on this page. Click "OK" to continue without saving. <br/> Warning: If you do not save this book, all edits done in this session may be lost.',
    bookNotSaved: '@@fr@@ This book is not saved yet. Click "Save" icon to save this book.',
    webmapCountStatus: "@@fr@@ ${start} - ${end} of ${total}",
    noWebmapFound: "@@fr@@ No map found",
    loadingWebmap: "@@fr@@ Loading...",
    shareBtnText: "@@fr@@ Share",
    shareBookTitle: "@@fr@@ Share Book",
    shareBookDialogTitle: "@@fr@@ Sharing Options",
    shareToOrgText: "@@fr@@ Organization",
    shareToEveryoneText: "@@fr@@ Everyone (public)",
    protectCopyBookText: "@@fr@@ Copy protect this book",
    copyRestricted: "@@fr@@ Cannot copy, the owner of this book has protected it from copying.",
    orientationNotSupported: "@@fr@@ App does not support this orientation",
    coverPageText: "@@fr@@ Cover page",
    contentPageText: "@@fr@@ Content page",
    webmapSearchBtnText: "@@fr@@ Go",
    printTitle: "@@fr@@ print",
    webmapDialogTitle: "@@fr@@ Map",
    HTMLDialogTitle: "@@fr@@ HTML",
    imageDialogTitle: "@@fr@@ Image",
    logoDialogTitle: "@@fr@@ Logo",
    textDialogTitle: "@@fr@@ Text",
    flickrDialogTitle: "@@fr@@ Flickr",
    videoDialogTitle: "@@fr@@ Video",
    webmapModuleTitleText: "@@fr@@ Map title goes here",
    webmapModuleCaptionText: "@@fr@@ Map caption goes here",
    textModuleDefaultText: "@@fr@@ Enter text here",
    HTMLModuleDefaultText: "@@fr@@ <p>Add HTML here</p>",
    videoModuleTitleText: "@@fr@@ Video title",
    videoModuleCaptionText: "@@fr@@ The video caption",
    dateModuleText: "@@fr@@ Date and/or other information here",
    subtitleModuleText: "@@fr@@ This is a subtitle or brief descriptive blurb about my map book. It's optional, but recommended. People will get a better sense of what the book is about if there's a descriptive subtitle here.",
    printPageTitle: "@@fr@@ Print Book",
    modulesNotLoaded: "@@fr@@ All modules are not loaded yet",
    arcgisOptionText: "@@fr@@ ArcGIS Online",
    myContentOptionText: "@@fr@@ My Content",
    organizationOptionText: "@@fr@@ My Organization",
    errorMessages: {
        webmapSearchFailed: "@@fr@@ An error occurred while searching the map",
        updatingItemError: "@@fr@@ Updating of the selected item failed",
        fieldInputIsNotValid: "@@fr@@ Invalid input",
        addingItemError: "@@fr@@ Adding new item failed",
        deletingItemError: "@@fr@@ Deleting selected item failed",
        copyItemError: "@@fr@@ Copying of selected item failed",
        contentQueryError: "@@fr@@ Failed to load user contents",
        webmapError: "@@fr@@ An error occurred while loading the map",
        permissionDenied: "@@fr@@ You do not have permissions to access this resource.",
        shareItemError: "@@fr@@ Updating selected item failed",
        organizationNotSet: "@@fr@@ Please configure your URL for your ArcGIS Online Organization or Portal for ArcGIS site.",
        configurationError: "@@fr@@ Please check your configuration",
        groupIdNotConfigured: "@@fr@@ Group id is not configured."
    }
});
