/*global define */
/*jslint browser:true,sloppy:true,nomen:true,unparam:true,plusplus:true,indent:4 */
/*
 | Copyright 2013 Esri
 |
 | Licensed under the Apache License, Version 2.0 (the "License");
 | you may not use this file except in compliance with the License.
 | You may obtain a copy of the License at
 |
 |    http://www.apache.org/licenses/LICENSE-2.0
 |
 | Unless required by applicable law or agreed to in writing, software
 | distributed under the License is distributed on an "AS IS" BASIS,
 | WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 | See the License for the specific language governing permissions and
 | limitations under the License.
 */
define({
    root: {
        noPages: "No pages found",
        tocContentsCaption: "Contents",
        homeTitle: "Home",
        addPageTitle: "Add Page",
        alertDialogTitle: "Alert",
        confirmDialogTitle: "Confirm",
        downloadBookTitle: "Download Book",
        refreshBookTitle: "Refresh",
        editTitle: "Edit Book",
        deleteTitle: "Delete Page",
        descriptionNotAvailable: "summary is not available",
        removeBookTitle: "Remove Book",
        tocTitle: "Contents",
        addPageText: "Add",
        addBookTitle: "New Book",
        saveBookShelf: "Save Book",
        copyBookShelf: "Copy Book",
        defaultItemId: "newItem",
        contentsPageTitle: "Contents",
        pageRequireMessage: "Page Title is required",
        pageText: "Page",
        ofText: "of",
        okButtonText: "OK",
        saveButtonText: "Save",
        cancelButtonText: "Cancel",
        closeButtonTitle: "Close",
        untitled: "Untitled",
        legendTitle: "Legend",
        fullScreen: "Toggle full screen",
        dndModuleText: "Drag and Drop Modules",
        selectAnyLayout: "Select a page layout",
        fieldIsEmpty: "Field can not be empty",
        webMapIconTitle: "Map",
        freeFormIconTitle: "HTML",
        textAreaIconTitle: "Text Area",
        imageIconTitle: "Image",
        videoIconTitle: "Video",
        flickrIconTitle: "Flickr",
        editMentEditTitle: "Edit",
        editMentDeleteTitle: "Delete",
        confirmModuleDeleting: "Do you want to delete this module?",
        authorName: "Author name",
        settingDialogTitle: "Edit ${modType}",
        mapbookDefaultTitle: "Briefing Book Title Goes Here",
        confirmPageDeleting: "This page will be removed. Click Ok to confirm.",
        confirmCopyOfSelectedBook: "Do you want to copy this book?",
        confirmDeletingOfSelectedBook: "${bookName} will be removed. Click 'OK' to confirm removal.",
        confirmAppReloading: "Briefing book gallery will be reloaded and you may lose the edits.",
        validateBookOwner: "You do not have permission to edit this book.",
        validateOrganizationUser: "You are not the member of this Organization.",
        copyKeyword: "Copy - ",
        signInText: "Sign In",
        signOutText: "Sign Out",
        unitInPixel: " (px)",
        unLockBookTitle: "Unlocked Book",
        lockBookTitle: "Locked Book",
        selectedWebmapText: "Currently displaying <b>${webmapName}</b>. Click 'Select map' to choose a different map",
        selectWebmapBtnText: "Select map",
        selectWebmapDialogTitle: "Select map",
        searchWebmapPlaceHolder: "Enter search term",
        nextWebmapPageText: "Next",
        preWebmapPageText: "Previous",
        validateUnSavedEdits: 'There are unsaved changes in this book. Click "Cancel" to stay on this page. Click "OK" to continue without saving. <br/> Warning: If you do not save this book, all edits done in this session may be lost.',
        bookNotSaved: 'This book is not saved yet. Click "Save" icon to save this book.',
        webmapCountStatus: "${start} - ${end} of ${total}",
        noWebmapFound: "No map found",
        loadingWebmap: "Loading...",
        shareBtnText: "Share",
        shareBookTitle: "Share Book",
        shareBookDialogTitle: "Sharing Options",
        shareToOrgText: "Organization",
        shareToEveryoneText: "Everyone (public)",
        protectCopyBookText: "Copy protect this book",
        copyRestricted: "Cannot copy, the owner of this book has protected it from copying.",
        orientationNotSupported: "App does not support this orientation",
        coverPageText: "Cover page",
        contentPageText: "Content page",
        webmapSearchBtnText: "Go",
        printTitle: "print",
        webmapDialogTitle: "Map",
        HTMLDialogTitle: "HTML",
        imageDialogTitle: "Image",
        logoDialogTitle: "Logo",
        textDialogTitle: "Text",
        flickrDialogTitle: "Flickr",
        videoDialogTitle: "Video",
        webmapModuleTitleText: "Map title goes here",
        webmapModuleCaptionText: "Map caption goes here",
        textModuleDefaultText: "Enter text here",
        HTMLModuleDefaultText: "<p>Add HTML here</p>",
        videoModuleTitleText: "Video title",
        videoModuleCaptionText: "The video caption",
        dateModuleText: "Date and/or other information here",
        subtitleModuleText: "This is a subtitle or brief descriptive blurb about my map book. It's optional, but recommended. People will get a better sense of what the book is about if there's a descriptive subtitle here.",
        printPageTitle: "Print Book",
        modulesNotLoaded: "All modules are not loaded yet",
        arcgisOptionText: "ArcGIS Online",
        myContentOptionText: "My Content",
        organizationOptionText: "My Organization",
        errorMessages: {
            webmapSearchFailed: "An error occurred while searching the map",
            updatingItemError: "Updating of the selected item failed",
            fieldInputIsNotValid: "Invalid input",
            addingItemError: "Adding new item failed",
            deletingItemError: "Deleting selected item failed",
            updaingItemError: "Updating selected item failed",
            copyItemError: "Copying of selected item failed",
            contentQueryError: "Failed to load user contents",
            webmapError: "An error occurred while loading the map",
            permissionDenied: "You do not have permissions to access this resource.",
            shareItemError: "Updating selected item failed",
            organizationNotSet: "Please configure your URL for your ArcGIS Online Organization or Portal for ArcGIS site.",
            configurationError: "Please check your configuration",
            groupIdNotConfigured: "Group id is not configured."
        }
    },
    fr: true
});
